# This is a boilerplate parameters config generated for pipeline 'ingest_financial_data'
# using Kedro 0.19.6.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.6/configuration/parameters.html

base_configuration:
  initial_cash: 10000.0
  risk_free_rate: 0.01
  slippage: 0.001
  commission: 0.0005
  currency: "USD"
  datetime_zone: "America/New_York"
  close_order_time: "15:30"
  risk_management:
    atr_period: 14
    support_resistance_window: 20
    risk_per_trade: 0.01
    distance_level: 0.02

strategies_configuration:
  SmaCross:
    short_window: 10
    long_window: 30
  BollingerBands:
    window: 20
    num_std_dev: 2
